//! What happens while you're away: dimming, locking, screen off, suspend.
//! `vela idle` turns the `[idle]` settings into a hypridle config and runs
//! hypridle with it, restarting it when the settings change (hypridle
//! doesn't reload its config).

use crate::config::Idle;
use std::fmt::Write;

fn seconds(on: bool, minutes: f64) -> Option<u64> {
    on.then(|| ((minutes * 60.0).round() as u64).max(1))
}

fn listener(out: &mut String, timeout: u64, on_timeout: &str, on_resume: Option<&str>) {
    let _ = write!(out, "\nlistener {{\n    timeout = {timeout}\n    on-timeout = {on_timeout}\n");
    if let Some(r) = on_resume {
        let _ = writeln!(out, "    on-resume = {r}");
    }
    out.push_str("}\n");
}

/// hypridle config for these settings. `kbd` is the keyboard backlight LED
/// (e.g. `tpacpi::kbd_backlight`), dimmed together with the screen.
pub fn hypridle_conf(idle: &Idle, kbd: Option<&str>) -> String {
    let mut out = String::from(
        "# Generated by vela from ~/.config/vela/config.toml [idle]; edits here are overwritten.\n\ngeneral {\n    lock_cmd = pidof hyprlock || hyprlock\n",
    );
    if idle.lock_before_sleep {
        out.push_str("    before_sleep_cmd = loginctl lock-session\n");
    }
    out.push_str("    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({action = \"on\"})'\n}\n");
    if let Some(t) = seconds(idle.dim, idle.dim_after_min) {
        listener(&mut out, t, "brightnessctl -s set 10", Some("brightnessctl -r"));
        if let Some(k) = kbd {
            listener(&mut out, t, &format!("brightnessctl -sd {k} set 0"), Some(&format!("brightnessctl -rd {k}")));
        }
    }
    if let Some(t) = seconds(idle.lock, idle.lock_after_min) {
        listener(&mut out, t, "loginctl lock-session", None);
    }
    if let Some(t) = seconds(idle.screen_off, idle.screen_off_after_min) {
        listener(
            &mut out,
            t,
            "hyprctl dispatch 'hl.dsp.dpms({action = \"off\"})'",
            Some("hyprctl dispatch 'hl.dsp.dpms({action = \"on\"})'"),
        );
    }
    if let Some(t) = seconds(idle.suspend, idle.suspend_after_min) {
        listener(&mut out, t, "systemctl suspend", None);
    }
    out
}

/// First keyboard backlight LED in /sys/class/leds.
pub fn keyboard_backlight() -> Option<String> {
    let mut names: Vec<String> = std::fs::read_dir("/sys/class/leds")
        .ok()?
        .filter_map(|e| e.ok()?.file_name().into_string().ok())
        .filter(|n| n.ends_with("kbd_backlight"))
        .collect();
    names.sort();
    names.into_iter().next()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::Idle;

    #[test]
    fn default_matches_the_hypridle_sample() {
        let conf = hypridle_conf(&Idle::default(), Some("rgb:kbd_backlight"));
        assert!(conf.contains("lock_cmd = pidof hyprlock || hyprlock"));
        assert!(conf.contains("before_sleep_cmd = loginctl lock-session"));
        assert!(conf.contains("timeout = 150\n    on-timeout = brightnessctl -s set 10"));
        assert!(conf.contains("brightnessctl -sd rgb:kbd_backlight set 0"));
        assert!(conf.contains("timeout = 300\n    on-timeout = loginctl lock-session"));
        assert!(conf.contains("timeout = 330\n    on-timeout = hyprctl dispatch"));
        assert!(conf.contains("timeout = 1800\n    on-timeout = systemctl suspend"));
    }

    #[test]
    fn switched_off_means_never() {
        let idle = Idle {
            suspend: false,
            dim: false,
            ..Idle::default()
        };
        let conf = hypridle_conf(&idle, Some("rgb:kbd_backlight"));
        assert!(!conf.contains("systemctl suspend"), "never suspends");
        assert!(!conf.contains("brightnessctl"), "never dims");
        assert!(conf.contains("loginctl lock-session"));
    }

    #[test]
    fn no_keyboard_backlight_and_no_lock_before_sleep() {
        let idle = Idle {
            lock_before_sleep: false,
            ..Idle::default()
        };
        let conf = hypridle_conf(&idle, None);
        assert!(!conf.contains("kbd_backlight"));
        assert!(!conf.contains("before_sleep_cmd"));
        assert!(conf.contains("after_sleep_cmd"));
    }

    #[test]
    fn minutes_become_whole_seconds() {
        let idle = Idle {
            lock_after_min: 0.75,
            ..Idle::default()
        };
        assert!(hypridle_conf(&idle, None).contains("timeout = 45\n"));
    }
}
